import os, platform

is_mac = "Darwin" in platform.platform()

app_name = os.path.split(os.path.abspath("."))[1]

steinberg_path = os.path.abspath(os.path.join("..", "Steinberg"))
vst_cpp_path = os.path.join(steinberg_path, "public.sdk", "source", "vst2.x")

sources = Glob('*.cpp') + Glob(os.path.join(vst_cpp_path, "*.cpp"))

if not is_mac:
    sources += Glob("*.def")


if is_mac:
    link_flags = "-arch i386 -arch x86_64"
    c_flags = "{} -Wall -pedantic".format(link_flags)
else:
    link_flags = ""
    c_flags = ""

env = Environment(
    CPPFLAGS=c_flags,
    LINKFLAGS=link_flags,
    CPPPATH=[vst_cpp_path, steinberg_path]
)

env.SharedLibrary(target=app_name, source=sources)
